collections:
  - name: "settings"
    label: "Site Settings"
    editor:
      preview: false
    files:
      - label: "Metadata"
        name: "metadata"
        file: "content/settings/metadata.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Site URL", name: "siteUrl", widget: "string" }
